chapter_18/pizzeria_project/pizzas/urls.py
"""Defines URL patterns for Pizzeria."""

from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all pizzas
    path('pizzas/', views.pizzas, name='pizzas'),
    # Detail page for a single pizza
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza')
]

chapter_18/pizzeria_project/pp_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('pizzas.urls'))
]

chapter_18/pizzeria_project/pizzas/models.py
from django.db import models


class Pizza(models.Model):
    """A pizza."""
    name = models.CharField(max_length=50)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name


class Topping(models.Model):
    """A class to hold toppings for the pizza."""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        """Return a simple string representing the toppings."""
        if len(self.name) > 50:
            return f"{self.name[:50]}..."
        else:
            return f"{self.name}"

chapter_18/pizzeria_project/pizzas/views.py
from django.shortcuts import render

from .models import Pizza


def index(request):
    """The home page for Pizzeria."""
    return render(request, 'pizzas/index.html')


def pizzas(request):
    """Shows all pizzas."""
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)


def pizza(request, pizza_id):
    """Shows a single pizza and all its toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

chapter_18/pizzeria_project/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a> -
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

chapter_18/pizzeria_project/pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% block content %}
<p>Pizzeria Pages is problem 18-8 of Python Crash Course (3rd Edition) by Eric Matthes.</p>
{% endblock content %}

chapter_18/pizzeria_project/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

<p>Pizza: {{ pizza.name }}</p>

<p>Toppings:</p>
<ul>
    {% for topping in toppings %}
    <li>
        <p>{{ topping.name|linebreaks }}</p>
    </li>
    {% empty %}
    <li>There are no toppings for this pizza.</li>
    {% endfor %}
</ul>

{% endblock content %}

chapter_18/pizzeria_project/pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}

<p>Pizzas</p>
<ul>
    {% for pizza in pizzas %}
    <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza.name }}</a>
    </li>
    {% empty %}
    <li>No pizzas have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}